In [3]:
import numpy as np
a=[1,2,3,4]
b=[1,2,3,4]
c=np.add(a,b)
d=np.subtract(a,b)
e=np.multiply(a,b)
f=np.divide(a,b)
print("addition is ",c)
print("subtraction is ",d)
print("multiplication is ",e)
print("division is ",f)


addition is  [2 4 6 8]
subtraction is  [0 0 0 0]
multiplication is  [ 1  4  9 16]
division is  [1. 1. 1. 1.]


In [6]:
a=[1,2,3,5]
b=np.mean(a)
print("the mean is ",b)

the mean is  2.75


In [8]:
a=[1,2,3,4]
b=[5,6,7,8]
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
a=[1,2,3,4]
b=[2,3,4,5]
c=np.dot(a,b)
print("the dot product is ",c)

the dot product is  40


In [21]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
np.ones((5,7),dtype=np.int64)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [24]:
np.zeros((3,3),dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
a=[3,4,5,6,7,8,9,2,1]

np.std(a)

np.float64(2.581988897471611)

In [34]:
a=[1,9,4,5,5,6,6,7]
c=np.mean(a)
print(c)
print(np.std(a))

5.375
2.1758618981911515


In [40]:
a=np.arange(1,13)
print(a)
np.reshape(a,(4,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
a=['M','F',5,'F','M','F']
print(np.unique(a))


['5' 'F' 'M']


In [54]:
a=np.array([1,2,3,4,5,6])
print(a[a>3])

[4 5 6]
